# Generated by Django 4.2.1 on 2023-05-29 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eatnnovationApp', '0002_sale_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='total',
            new_name='total_amount',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
