# Generated by Django 4.2.1 on 2023-05-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eatnnovationApp', '0003_sale_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='total',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='user',
            new_name='username',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
