# Generated by Django 4.2.1 on 2023-05-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatnnovationApp', '0003_rename_total_invoice_total_amount_delete_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
