# Generated by Django 4.2.1 on 2023-05-29 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eatnnovationApp', '0004_invoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='date',
        ),
    ]
