# Generated by Django 4.2.1 on 2023-05-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eatnnovationApp', '0004_rename_total_invoice_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='username',
            new_name='user',
        ),
    ]
